"""Station 3 - Sentiment model: the AlphaStream FinSent lexicon, headline
scoring, and the sector sentiment index.

Design:
    * Baseline model is VADER (nltk), the model the course baseline uses.
    * AlphaStream FinSent is a curated finance-aware extension: single words
      enter the analyser's lexicon, multi-word phrases enter VADER's
      SPECIAL_CASES (with a small supporting head word so the phrase is
      actually looked up), and finance intensity words enter BOOSTER_DICT.
      Nothing is stripped from the text before scoring - VADER reads casing,
      punctuation, and negation, and stripping them destroys the signal.
    * Headlines are scored per unique title (many rows repeat a title across
      tickers), aggregated to a ticker-day mean, then to an equal-weight
      sector index. Ticker-days with no headlines contribute neutral (0) to
      the sector mean; we also report the fraction of names with news that day
      so coverage is visible.
    * Look-ahead safety: the published index (and every downstream signal) is
      lagged by one equity trading day, so a trade decided on day t uses only
      sentiment from day t-1 or earlier.

The lexicon itself is curated student work: candidate terms were generated by
an AI assistant, then reviewed, pruned, and valence-checked by hand against a
sample of real project headlines (see ai/log_sentiment_lexicon.md).
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# AlphaStream FinSent lexicon (curated finance extension)
# ---------------------------------------------------------------------------

# Single words, VADER valence scale (-4 to +4). Only terms VADER does not hold
# (or holds with a non-finance valence) are listed.
FINSENT_WORDS: dict[str, float] = {
    "beat": 1.6, "beats": 1.8, "miss": -1.6, "misses": -1.6,
    "outperform": 1.8, "underperform": -1.8, "buyback": 1.3, "buybacks": 1.3,
    "downgrade": -2.0, "downgrades": -2.0, "upgrade": 2.0, "upgrades": 2.0,
    "guidance": 0.0, "profitability": 0.6, "recession": -2.2,
    "recovery": 1.7, "rallied": 1.9, "tumbled": -2.2, "soared": 2.2,
    "plunged": -2.4, "surged": 2.2, "slumped": -2.1, "climbed": 1.5,
    "slid": -1.6, "spiked": 1.1, "wipeout": -2.8, "takeover": 1.2,
    "lawsuit": -2.2, "sanction": -1.6, "sanctions": -1.6, "tariff": -1.4,
    "tariffs": -1.4, "stimulus": 1.5, "quantitative": 0.0, "hawkish": -1.6,
    "dovish": 1.4, "volatility": -0.8, "headwind": -1.3, "headwinds": -1.3,
    "tailwind": 1.5, "tailwinds": 1.5, "outlook": 0.3, "shortage": -1.6,
    "surplus": 1.1, "defaults": -2.4, "bankruptcy": -3.0, "bankrupt": -2.8,
    "delisting": -2.6, "turnaround": 1.8, "momentum": 1.3, "breakout": 1.9,
    "breakdown": -1.9, "bullish": 2.0, "bearish": -2.0, "investor": 0.3,
    "traders": 0.2, "warn": -1.4, "warns": -1.4, "caution": -1.0,
    "cautious": -1.2, "risky": -1.6, "defensive": 0.5, "yield": 0.4,
    "yields": 0.4, "inflation": -0.8, "deflation": -1.4, "ratecut": 1.6,
    "ratehike": -1.4, "dividend": 1.2, "dividends": 1.2,
}

# Multi-word phrases, stored in VADER SPECIAL_CASES.
FINSENT_PHRASES: dict[str, float] = {
    "earnings beat": 2.2, "earnings miss": -2.2, "earnings growth": 1.6,
    "profit warning": -2.6, "profit warnings": -2.6, "price target": 0.4,
    "beats expectations": 2.4, "misses expectations": -2.4,
    "beats estimates": 2.4, "misses estimates": -2.4, "above expectations": 1.8,
    "below expectations": -1.8, "top line": 0.3, "bottom line": 0.3,
    "debt downgrade": -2.2, "credit upgrade": 2.0, "surprise profit": 2.2,
    "surprise loss": -2.4, "record high": 1.9, "record low": -2.0,
    "52-week high": 1.8, "52-week low": -2.0, "beats on revenue": 2.2,
    "strong demand": 2.0, "weak demand": -2.0, "supply chain": -0.8,
    "going concern": -2.8, "goingconcern": -2.8, "covenant breach": -2.6,
    "material weakness": -2.6, "insider buying": 1.6, "insider selling": -1.6,
    "hedge fund": 0.5, "market share": 0.8, "same-store sales": 0.6,
    "comparable sales": 0.6, "net income": 0.7, "operating margin": 0.8,
    "free cash flow": 1.0, "credit rating": 0.4, "speculative grade": -1.6,
    "investment grade": 1.2, "active investor": 1.1, "proxy fight": -1.4,
    "shareholder return": 1.6, "dividend cut": -2.2, "dividend raise": 1.8,
    "stock buyback": 1.8, "buyback program": 1.8, "layoff": -1.6,
    "layoffs": -1.8, "job cuts": -2.0, "restructuring": -1.0,
    "regulatory probe": -2.2, "regulatory approval": 1.6,
    "antitrust suit": -2.0, "antitrust probe": -2.0, "class action": -2.2,
    "product recall": -2.6, "data breach": -2.8, "cyberattack": -2.8,
    "cyber attack": -2.8, "activist investor": 0.8, "record quarter": 2.0,
    "revenue growth": 1.8, "margin expansion": 1.8, "cost cutting": 1.0,
    "cost cutting program": 1.2, "ahead of estimates": 1.6,
    "in line with estimates": 0.2, "below the consensus": -1.4,
    "above the consensus": 1.4, "warns of": -1.8, "flags risk": -1.6,
    "flags risk to": -1.6, "sees risk": -1.2, "raised guidance": 2.2,
    "cut guidance": -2.2, "lowered guidance": -2.2, "reaffirms guidance": 0.6,
    "lifts outlook": 2.0, "cuts outlook": -2.0, "debt restructuring": -1.4,
}

# Finance intensity words that strengthen the word after them.
FINSENT_BOOSTERS: dict[str, float] = {
    "sharply": 1.0, "materially": 1.0, "steeply": 1.0, "significantly": 1.0,
    "modestly": -1.0, "marginally": -1.0, "slightly": -1.0,
}


@lru_cache(maxsize=4)
def build_vader() -> object:
    """Return a plain VADER analyser (baseline)."""
    import nltk
    nltk.download("vader_lexicon", quiet=True)
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    return SentimentIntensityAnalyzer()


@lru_cache(maxsize=4)
def build_finsent() -> object:
    """Return a VADER analyser extended with the AlphaStream FinSent lexicon.

    Words update the analyser's own lexicon dict. Phrases need two steps:
    VADER only looks for a stored phrase where the token is already a
    dictionary hit, so each phrase's head word (its last token) must also have
    a tiny lexicon entry. Booster and phrase stores live on the analyser's
    constants object (NLTK >= 3.8) or as module globals (older NLTK).
    """
    import nltk
    nltk.download("vader_lexicon", quiet=True)
    from nltk.sentiment.vader import SentimentIntensityAnalyzer

    analyzer = SentimentIntensityAnalyzer()
    analyzer.lexicon.update(FINSENT_WORDS)

    constants = getattr(analyzer, "constants", None)
    if constants is None:
        import nltk.sentiment.vader as vader_module
        constants = vader_module

    phrase_store = getattr(constants, "SPECIAL_CASE_IDIOMS", None)
    if phrase_store is None:
        phrase_store = getattr(constants, "SPECIAL_CASES", {})
    booster_store = getattr(constants, "BOOSTER_DICT", {})

    for term, valence in FINSENT_PHRASES.items():
        head = term.split()[-1]
        if head not in analyzer.lexicon:
            analyzer.lexicon[head] = 0.1 if valence > 0 else -0.1
        if term not in phrase_store:
            phrase_store[term] = float(valence)

    for word, boost in FINSENT_BOOSTERS.items():
        if word not in booster_store:
            booster_store[word] = boost

    return analyzer


def score_text(analyzer: object, text: str) -> float:
    """Return the compound score (-1 to 1) for one text string."""
    if not text or not isinstance(text, str):
        return 0.0
    return float(analyzer.polarity_scores(text)["compound"])


def score_unique_titles(
    titles: pd.Series,
    *,
    cache_path: str | Path | None = None,
    analyzers: tuple[str, ...] = ("vader", "finsent"),
) -> pd.DataFrame:
    """Score every distinct headline once with the requested analyzers.

    Returns a DataFrame with columns [title, vader_compound, finsent_compound].
    If cache_path is given and holds all required titles, the cached frame is
    returned instead of re-scoring (build-time speed-up only).
    """
    unique = pd.Series(pd.unique(pd.Series(titles).dropna()), name="title")
    cache_path = Path(cache_path) if cache_path else None

    if cache_path is not None and cache_path.is_file():
        cached = pd.read_parquet(cache_path)
        if set(cached["title"]) >= set(unique):
            return cached

    out = pd.DataFrame({"title": unique})
    if "vader" in analyzers:
        vader = build_vader()
        out["vader_compound"] = [score_text(vader, t) for t in unique]
    if "finsent" in analyzers:
        finsent = build_finsent()
        out["finsent_compound"] = [score_text(finsent, t) for t in unique]

    if cache_path is not None:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        out.to_parquet(cache_path, index=False)
    return out


# ---------------------------------------------------------------------------
# Scoring and aggregation
# ---------------------------------------------------------------------------

def score_headlines(
    headlines: pd.DataFrame,
    equity_trading_dates: pd.DatetimeIndex,
    *,
    score_col: str = "finsent_compound",
    cache_path: str | Path | None = None,
) -> pd.DataFrame:
    """Score a cleaned headlines frame and return one row per headline.

    Returns a DataFrame with columns [date, ticker, sector, title,
    <score_col>], where date is the headline's aligned equity trading day.
    """
    trading_dates_sorted = pd.DatetimeIndex(sorted(equity_trading_dates))

    df = headlines.copy()
    df["date"] = pd.to_datetime(df["date"]).dt.tz_localize(None)
    idx = df["date"].map(
        lambda d: int(trading_dates_sorted.searchsorted(d, side="left"))
    ).to_numpy()
    idx = np.clip(idx, 0, len(trading_dates_sorted) - 1)
    df["trading_date"] = pd.DatetimeIndex([trading_dates_sorted[i] for i in idx])

    scored = score_unique_titles(df["title"], cache_path=cache_path)
    df = df.merge(scored, on="title", how="left")
    if score_col not in df.columns:
        raise ValueError(f"score_col {score_col!r} not produced by the analyzers")
    df[score_col] = df[score_col].fillna(0.0)
    out = df[["trading_date", "ticker", "sector", "title", score_col]].rename(
        columns={"trading_date": "date"}
    )
    return out.sort_values(["date", "ticker", "title"]).reset_index(drop=True)


def ticker_daily_sentiment(
    scored: pd.DataFrame,
    equity_trading_dates: pd.DatetimeIndex,
    *,
    score_col: str = "finsent_compound",
    lag: int = 1,
) -> pd.DataFrame:
    """Aggregate headline scores to a daily per-ticker panel.

    Returns a wide frame (date x ticker) of the mean compound score of each
    ticker's headlines aligned to its equity trading day. The frame is lagged
    by `lag` trading days so a decision on day t uses only sentiment from day
    t-lag or earlier. Ticker-days with no news carry NaN here (filled at the
    index stage).
    """
    daily = (
        scored.groupby(["date", "ticker"])[score_col]
        .mean()
        .reset_index()
    )
    wide = daily.pivot_table(index="date", columns="ticker", values=score_col)
    full_index = pd.DatetimeIndex(sorted(equity_trading_dates))
    wide = wide.reindex(full_index).sort_index()
    if lag > 0:
        wide = wide.shift(lag)
    return wide


def sector_sentiment_index(
    ticker_sentiment: pd.DataFrame,
    sector_map: pd.DataFrame,
    *,
    fill_missing: float = 0.0,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build the equal-weight sector sentiment index and a coverage table.

    ticker_sentiment: wide frame (date x ticker), already lagged.
    sector_map: DataFrame with [ticker, sector].

    For each trading day and sector, the index is the mean sentiment across
    the sector's tickers, with no-news ticker-days contributing `fill_missing`
    (neutral). Returns (index_long, coverage) where index_long has columns
    [date, sector, sentiment, n_covered, n_total] and a separate market-wide
    mean is computed by the caller.
    """
    sectors = sorted(sector_map["sector"].unique())
    available = list(ticker_sentiment.columns)
    rows = []
    coverage_rows = []
    for sector in sectors:
        tickers = sorted(set(
            sector_map.loc[sector_map["sector"] == sector, "ticker"]
        ) & set(available))
        n_total = int(sector_map.loc[sector_map["sector"] == sector, "ticker"].nunique())
        if not tickers:
            continue
        sub = ticker_sentiment[tickers].fillna(fill_missing)
        index = sub.mean(axis=1)
        covered = ticker_sentiment[tickers].notna().sum(axis=1)
        for date in index.index:
            rows.append({"date": date, "sector": sector, "sentiment": float(index.loc[date])})
            coverage_rows.append({
                "date": date, "sector": sector,
                "n_covered": int(covered.loc[date]),
                "n_total": n_total,
            })
    index_long = pd.DataFrame(rows)
    coverage = pd.DataFrame(coverage_rows)
    return index_long, coverage


def build_sentiment_index(
    headlines: pd.DataFrame,
    equity_trading_dates: pd.DatetimeIndex,
    sector_map: pd.DataFrame,
    *,
    score_col: str = "finsent_compound",
    lag: int = 1,
    cache_path: str | Path | None = None,
) -> dict[str, pd.DataFrame]:
    """Run the full sentiment pipeline and return all derived panels.

    Returns a dict with:
        scored              : per-headline scores
        ticker_daily_lag    : lagged ticker-day sentiment (wide)
        index_long          : long sector index (lagged, tradeable)
        index_wide          : pivot date x sector of the lagged index
        market_index        : market-wide mean across sectors (date, sentiment)
        coverage            : per sector-day news coverage
    """
    scored = score_headlines(
        headlines, equity_trading_dates, score_col=score_col, cache_path=cache_path
    )
    ticker_daily = ticker_daily_sentiment(
        scored, equity_trading_dates, score_col=score_col, lag=lag)
    index_long, coverage = sector_sentiment_index(ticker_daily, sector_map)

    index_wide = index_long.pivot_table(
        index="date", columns="sector", values="sentiment"
    ).sort_index()
    market_index = index_wide.mean(axis=1).rename("sentiment").reset_index()
    return {
        "scored": scored,
        "ticker_daily_lag": ticker_daily,
        "index_long": index_long,
        "index_wide": index_wide,
        "market_index": market_index,
        "coverage": coverage,
    }
